### PR TITLE
Generating a second pipeline + fixed types

### PR DESCRIPTION
**Pull request by jesper-friis**
- Generate second pipeline
- Fixed typos
- Some pylint fixes
- Preserve order when saving to yaml

### CODE REVIEW

**Review by francescalb — CHANGES_REQUESTED** [review]
I have problems running the second test. It seems that when loading the container a list is returned. For each of the items in the list it is expected that it is a dict, but it is a string.

here:
            for stype, conf in strategy.items():
                name = f"{name_suffix}_{stype}"

Does this not happen for you?

**Comment by jesper-friis** [comment]
> I have problems running the second test. It seems that when loading the container a list is returned. For each of the items in the list it is expected that it is a dict, but it is a string.
> 
> here: for stype, conf in strategy.items(): name = f"{name_suffix}_{stype}"
> 
> Does this not happen for you?

Works fine with Python 3.10 for me, but I get the same issue with 3.11. Must look into this...

**Comment by francescalb** [comment]
> > I have problems running the second test. It seems that when loading the container a list is returned. For each of the items in the list it is expected that it is a dict, but it is a string.
> > here: for stype, conf in strategy.items(): name = f"{name_suffix}_{stype}"
> > Does this not happen for you?
> 
> Works fine with Python 3.10 for me, but I get the same issue with 3.11. Must look into this...


Interesting, I have python3.10 so it is not the python version....

**Comment by jesper-friis** [comment]
> > > I have problems running the second test. It seems that when loading the container a list is returned. For each of the items in the list it is expected that it is a dict, but it is a string.
> > > here: for stype, conf in strategy.items(): name = f"{name_suffix}_{stype}"
> > > Does this not happen for you?
> > 
> > 
> > Works fine with Python 3.10 for me, but I get the same issue with 3.11. Must look into this...
> 
> Interesting, I have python3.10 so it is not the python version....

I think the issue was with the version of tripper and not Python. I have now added tripper master to requirements in pyproject.toml.

**Review by francescalb — APPROVED** [review]
Seems good so I think we can merge now. However, I do beleive it is important that we update the SS3 including wrappers to make what we want and then see if this works.

**Pull request merged**
